
name: gatsby deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: packages install
        run: npm install

      - name: gatsby build
        run: npm run build
        env:
          GH_API_KEY: ${{ secrets.API_KEY }}

      - name: CNAME copy
        run: cp CNAME public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/